import { useQuery } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/contexts/AuthContext";
import { useMemo } from "react";
import type { Signal, EnrichedSignal, PairAnalysisRow } from "@/types/trading";
import { rowToAnalysis } from "./_shared/row-to-analysis";

/**
 * Fallback risk/reward calculation for legacy rows that pre-date the
 * Phase 5 `risk_reward` column. Once all active signals have been
 * regenerated by the next generate-signals run, this can be removed
 * and consumers can rely on `signals.risk_reward` directly.
 *
 * TODO: remove after the first generate-signals run post-deploy.
 */
function computeRR(entry: number, sl: number, tp1: number): number {
  const risk = Math.abs(entry - sl);
  if (risk === 0) return 0;
  return Math.round((Math.abs(tp1 - entry) / risk) * 100) / 100;
}

/** Return the persisted risk_reward if present, else compute from prices. */
function resolveRiskReward(s: Signal): number {
  const persisted = (s as { risk_reward?: number | string | null }).risk_reward;
  if (persisted != null) return Number(persisted);
  return computeRR(Number(s.entry_price), Number(s.stop_loss), Number(s.take_profit_1));
}

/**
 * Pull a row's joined `pair_analyses` data, regardless of whether
 * Supabase returned it as a single object or a single-element array
 * (PostgREST varies based on FK direction and selectivity).
 */
function extractAnalysisRow(joined: unknown): PairAnalysisRow | null {
  if (!joined) return null;
  if (Array.isArray(joined)) return (joined[0] as PairAnalysisRow | undefined) ?? null;
  return joined as PairAnalysisRow;
}

// ── Pair-level analyses lookup (kept for the `useSignals` enrichment fallback) ──

function usePairAnalyses() {
  const { user } = useAuth();

  return useQuery({
    queryKey: ["pair-analyses"],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("pair_analyses")
        .select("*")
        .order("created_at", { ascending: false });
      if (error) throw error;
      if (!data || data.length === 0) return null;

      // Keep only the latest analysis per pair
      const byPair: Record<string, PairAnalysisRow> = {};
      for (const row of data) {
        if (!byPair[row.pair]) byPair[row.pair] = row as PairAnalysisRow;
      }
      return byPair;
    },
    enabled: !!user,
    staleTime: 60_000,
  });
}

// ── Hooks ───────────────────────────────────────────────────────

export function useSignals() {
  const { user } = useAuth();
  const { data: analyses } = usePairAnalyses();

  const query = useQuery({
    queryKey: ["signals"],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("signals")
        .select("*")
        .order("created_at", { ascending: false });
      if (error) throw error;
      return data as Signal[];
    },
    enabled: !!user,
  });

  const enriched: EnrichedSignal[] = useMemo(() => {
    if (!query.data) return [];
    return query.data.map((s) => {
      const dbAnalysis = analyses?.[s.pair];
      const analysis = dbAnalysis ? rowToAnalysis(dbAnalysis) : null;
      return {
        ...s,
        analysis,
        riskReward: resolveRiskReward(s),
      };
    });
  }, [query.data, analyses]);

  return { ...query, signals: query.data ?? [], enriched };
}

export function useActiveSignals(limit = 6) {
  const { user } = useAuth();

  return useQuery({
    queryKey: ["signals-active", limit],
    queryFn: async () => {
      const { data } = await supabase
        .from("signals")
        .select("*")
        .eq("status", "active")
        .order("created_at", { ascending: false })
        .limit(limit);
      return (data ?? []) as Signal[];
    },
    enabled: !!user,
  });
}

/**
 * Returns active signals for a pair, each enriched with its FK-linked
 * pair_analyses row. This is the **single source of truth** for the
 * pair detail page: chart annotations, the setup card, and the signal
 * list all consume the same enriched record.
 */
export function useSignalsByPair(pair: string) {
  const { user } = useAuth();

  return useQuery<EnrichedSignal[]>({
    queryKey: ["signals-pair", pair],
    queryFn: async () => {
      // Join pair_analyses via the signal_id FK so each signal gets
      // its own analysis row (not the latest analysis for that pair name).
      const { data, error } = await supabase
        .from("signals")
        .select("*, pair_analyses!pair_analyses_signal_id_fkey(*)")
        .eq("pair", pair)
        .eq("status", "active")
        .order("created_at", { ascending: false });
      if (error) throw error;

      return (data ?? []).map((row) => {
        const { pair_analyses: joined, ...signalCols } = row as Signal & {
          pair_analyses: PairAnalysisRow | PairAnalysisRow[] | null;
        };
        const analysisRow = extractAnalysisRow(joined);
        const analysis = analysisRow ? rowToAnalysis(analysisRow) : null;
        return {
          ...(signalCols as Signal),
          analysis,
          riskReward: resolveRiskReward(signalCols as Signal),
        };
      });
    },
    enabled: !!user && !!pair,
  });
}

export function getQualityFromEnrichedSignal(signal: EnrichedSignal): string | null {
  return signal.analysis?.setupQuality ?? null;
}
