import { useState } from "react";
import { Link } from "react-router-dom";
import {
  Sheet,
  SheetContent,
  SheetHeader,
  SheetTitle,
  SheetDescription,
} from "@/components/ui/sheet";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import StatusBadge, { FreshnessBadge } from "@/components/ui/status-badge";
import { Button } from "@/components/ui/button";
import { TermTooltip } from "@/components/ui/term-tooltip";
import TakeTradeDialog from "@/components/trades/TakeTradeDialog";
import type { Freshness } from "@/lib/data-freshness";
import {
  getSignalAge,
  getAccountSuitability,
  getPrimaryRisk,
  getBeginnerFriendlyTag,
} from "@/lib/signal-presentation";
import { useRecentSetupLosses } from "@/hooks/use-journal";
import { useBeginnerMode } from "@/hooks/use-beginner-mode";
import type { GlossaryTerm } from "@/lib/glossary";
import { Calculator, Sparkles } from "lucide-react";
import {
  ArrowUpRight,
  ArrowDownRight,
  Ban,
  AlertTriangle,
  CheckCircle,
  XCircle,
  Shield,
  Zap,
} from "lucide-react";
import type { EnrichedSignal } from "@/pages/Signals";

interface Props {
  signal: EnrichedSignal | null;
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

export default function SignalDetailDrawer({ signal, open, onOpenChange }: Props) {
  const [takeTradeOpen, setTakeTradeOpen] = useState(false);
  // Phase 5 (improvement plan): how many recent losses the user has
  // journaled on this pair+setup. >= 2 surfaces the caution strip.
  // Hook must come before any conditional return — pass nullable
  // values so it self-disables when no signal is selected.
  const { count: recentLossCount } = useRecentSetupLosses(
    signal?.pair ?? null,
    signal?.setup_type ?? null,
  );
  // Phase 8: beginner-friendly badge is gated on `useBeginnerMode()` —
  // non-beginners don't need the extra label. Hook must run on every
  // render so it's called above the early return below.
  const isBeginner = useBeginnerMode();

  if (!signal) return null;

  const isLong = signal.direction === "long";
  const isNoTrade = signal.verdict === "no_trade";
  const analysis = signal.analysis;
  const quality = analysis?.setupQuality ?? null;
  const isAggressive = signal.confidence >= 75;

  // Phase 1 (improvement plan): trust signals derived from the
  // already-persisted analysis fields. Same heuristics used on the
  // dashboard top-trade card and the mobile signal card.
  const age = getSignalAge(signal);
  const suitability = getAccountSuitability(signal);
  const primaryRisk = getPrimaryRisk(signal);
  const beginnerTag = getBeginnerFriendlyTag(signal);

  // Phase 8/9: derive explanation heading + badge from persisted metadata.
  const explanationStatus = analysis?.explanationStatus ?? null;
  const explanationTitle =
    explanationStatus === "ai_success" ? "AI Explanation" : "Explanation";
  const explanationBadge: Freshness =
    explanationStatus === "ai_success"
      ? "live"
      : explanationStatus === "ai_failed"
      ? "cached"
      : "fallback";
  const explanationTooltip =
    explanationStatus === "ai_success"
      ? `Generated by ${analysis?.explanationModel ?? "Claude"} · prompt ${analysis?.explanationPromptVersion ?? "v1"}`
      : explanationStatus === "ai_failed"
      ? `AI call failed (${analysis?.explanationErrorCode ?? "unknown"}) — showing template`
      : explanationStatus === "ai_skipped"
      ? "AI not configured — showing template"
      : "Template explanation";

  return (
    <Sheet open={open} onOpenChange={onOpenChange}>
      <SheetContent side="right" className="w-full sm:max-w-lg overflow-y-auto">
        <SheetHeader className="pb-4 border-b border-border">
          <div className="flex items-center justify-between">
            <SheetTitle className="text-lg font-bold">{signal.pair}</SheetTitle>
            <div className="flex items-center gap-2">
              {quality && (
                <StatusBadge variant={quality === "A+" || quality === "A" ? "bullish" : quality === "B" ? "neutral" : "bearish"}>
                  {quality}
                </StatusBadge>
              )}
              <StatusBadge
                variant={
                  signal.status === "active" ? "active"
                  : signal.status === "triggered" ? "triggered"
                  : signal.status === "invalidated" ? "bearish"
                  : "expired"
                }
              >
                {signal.status}
              </StatusBadge>
            </div>
          </div>
          <SheetDescription className="flex items-center gap-2 mt-1 flex-wrap">
            {isNoTrade ? (
              <span className="flex items-center gap-1 text-warning font-medium">
                <Ban className="h-3.5 w-3.5" /> No Trade
              </span>
            ) : (
              <span className={`flex items-center gap-1 font-medium ${isLong ? "text-bullish" : "text-bearish"}`}>
                {isLong ? <ArrowUpRight className="h-3.5 w-3.5" /> : <ArrowDownRight className="h-3.5 w-3.5" />}
                {isLong ? "Long" : "Short"}
              </span>
            )}
            <span className="text-muted-foreground">·</span>
            <span className="text-muted-foreground">{signal.timeframe}</span>
            <span className="text-muted-foreground">·</span>
            <span className={`text-xs font-medium ${isAggressive ? "text-warning" : "text-primary"}`}>
              {isAggressive ? (
                <span className="flex items-center gap-1"><Zap className="h-3 w-3" /> Aggressive</span>
              ) : (
                <span className="flex items-center gap-1"><Shield className="h-3 w-3" /> Conservative</span>
              )}
            </span>
            <span className="text-muted-foreground">·</span>
            <span className="text-[11px] text-muted-foreground">{age.label}</span>
            {age.staleness !== "fresh" && (
              <StatusBadge
                variant={age.staleness === "stale" ? "bearish" : "pending"}
                title={`Generated ${age.label} — market conditions may have shifted.`}
              >
                {age.staleness === "stale" ? "Stale" : "Aging"}
              </StatusBadge>
            )}
            {suitability.level === "real" && (
              <StatusBadge variant="bullish" title={suitability.reason}>Real-account suitable</StatusBadge>
            )}
            {suitability.level === "demo_only" && (
              <StatusBadge variant="pending" title={suitability.reason}>Demo only</StatusBadge>
            )}
            {/* Phase 8 (improvement plan): beginner-only badge — fires
                when the engine's heuristic agrees the setup is strong
                enough to be a beginner-friendly pick (A/A+ quality,
                70%+ confidence, R:R >= 2). Gated on isBeginner so the
                trust-signal row stays compact for advanced users. */}
            {isBeginner && beginnerTag.friendly && (
              <StatusBadge
                variant="bullish"
                className="gap-1"
                title={beginnerTag.reason}
              >
                <Sparkles className="h-2.5 w-2.5" /> Beginner-friendly
              </StatusBadge>
            )}
          </SheetDescription>
        </SheetHeader>

        <div className="space-y-5 pt-5">
          {/* Phase 18.3: Take Trade CTA (hidden for no_trade signals).
              Phase 6 (improvement plan): pair the primary action with a
              "Calculate lot size" shortcut so a beginner can step into
              the full Calculator (with its education sidebar) before
              committing. The button is the primary; the link is the
              alternate path. */}
          {!isNoTrade && (
            <div className="flex flex-col sm:flex-row gap-2">
              <Button
                className="flex-1 gap-1.5"
                onClick={() => setTakeTradeOpen(true)}
              >
                <Zap className="h-4 w-4" /> Take This Trade
              </Button>
              <Button
                asChild
                variant="outline"
                className="gap-1.5"
              >
                <Link
                  to={`/calculator?pair=${encodeURIComponent(signal.pair)}&entry=${signal.entry_price}&sl=${signal.stop_loss}`}
                >
                  <Calculator className="h-4 w-4" /> Calculate lot size
                </Link>
              </Button>
            </div>
          )}

          {/* No Trade Warning */}
          {isNoTrade && (
            <div className="rounded-lg border border-warning/30 bg-warning/10 p-4">
              <div className="flex items-center gap-2 mb-2">
                <Ban className="h-4 w-4 text-warning" />
                <span className="font-semibold text-warning text-sm">No Trade Recommended</span>
              </div>
              <p className="text-xs text-muted-foreground leading-relaxed">
                {analysis?.noTradeReason || signal.ai_reasoning}
              </p>
            </div>
          )}

          {/* Phase 1 (improvement plan): top risk callout — promotes the
              first reason-against from the analysis so users see what
              could go wrong before they study the price levels. */}
          {!isNoTrade && primaryRisk && (
            <div className="rounded-lg border border-warning/30 bg-warning/10 p-3">
              <div className="flex items-start gap-2">
                <AlertTriangle className="h-4 w-4 text-warning mt-0.5 shrink-0" />
                <div>
                  <p className="text-[11px] uppercase tracking-wider text-warning font-semibold mb-1">
                    Why this could fail
                  </p>
                  <p className="text-xs text-muted-foreground leading-relaxed">{primaryRisk}</p>
                </div>
              </div>
            </div>
          )}

          {/* Phase 7 (improvement plan): stale-signal banner — mirrors
              the dashboard's TopTradeCard banner so a user reading the
              full drawer sees the same warning. */}
          {age.staleness === "stale" && (
            <div className="rounded-lg border border-bearish/30 bg-bearish/[0.06] p-3">
              <div className="flex items-start gap-2">
                <AlertTriangle className="h-4 w-4 text-bearish mt-0.5 shrink-0" />
                <div>
                  <p className="text-[11px] uppercase tracking-wider text-bearish font-semibold mb-1">
                    Stale signal
                  </p>
                  <p className="text-xs text-muted-foreground leading-relaxed">
                    This signal was generated {age.label}. Market conditions may have shifted — re-check the chart and the price levels before acting on it.
                  </p>
                </div>
              </div>
            </div>
          )}

          {/* Phase 5 (improvement plan): recurring-struggle caution.
              Surfaces only when the user has 2+ journaled losses on
              this pair+setup in the last 30 days. Doesn't block — just
              raises the bar for taking the trade. */}
          {!isNoTrade && recentLossCount >= 2 && (
            <div className="rounded-lg border border-bearish/30 bg-bearish/[0.06] p-3">
              <div className="flex items-start gap-2">
                <AlertTriangle className="h-4 w-4 text-bearish mt-0.5 shrink-0" />
                <div>
                  <p className="text-[11px] uppercase tracking-wider text-bearish font-semibold mb-1">
                    You've struggled here recently
                  </p>
                  <p className="text-xs text-muted-foreground leading-relaxed">
                    {recentLossCount} losing {signal.setup_type || "setup"} trade{recentLossCount === 1 ? "" : "s"} on {signal.pair} in the last 30 days. Re-read your journal lessons before sizing this one.
                  </p>
                </div>
              </div>
            </div>
          )}

          {/* Price Levels */}
          <Section title="Price Levels">
            <div className="grid grid-cols-2 gap-3">
              <LevelRow label="Entry" value={signal.entry_price} />
              <LevelRow label="Stop Loss" term="stop_loss" value={signal.stop_loss} className="text-bearish" />
              <LevelRow label="TP1" term="take_profit" value={signal.take_profit_1} className="text-bullish" />
              <LevelRow label="TP2" term="take_profit" value={signal.take_profit_2 ?? "—"} className="text-bullish" />
              <LevelRow label="TP3" term="take_profit" value={signal.take_profit_3 ?? "—"} className="text-bullish" />
              <LevelRow label="R:R" term="risk_reward" value={`${signal.riskReward}R`} />
            </div>
          </Section>

          {/* Setup Info */}
          <Section title="Setup Info">
            <div className="space-y-2 text-xs">
              <div className="flex justify-between">
                <span className="text-muted-foreground">
                  <TermTooltip term="setup_quality">Setup Type</TermTooltip>
                </span>
                <span className="text-foreground font-medium">{signal.setup_type || analysis?.setupType || "—"}</span>
              </div>
              <div className="flex justify-between items-center">
                <span className="text-muted-foreground">
                  <TermTooltip term="confidence">Confidence</TermTooltip>
                </span>
                <div className="flex items-center gap-2">
                  <div className="w-16 bg-muted rounded-full h-1.5">
                    <div
                      className={`h-1.5 rounded-full ${signal.confidence >= 70 ? "bg-bullish" : signal.confidence >= 50 ? "bg-warning" : "bg-bearish"}`}
                      style={{ width: `${signal.confidence}%` }}
                    />
                  </div>
                  <span className="text-foreground font-medium">{signal.confidence}%</span>
                </div>
              </div>
              {analysis?.entryZone && (
                <div className="flex justify-between">
                  <span className="text-muted-foreground">Entry Zone</span>
                  <span className="text-foreground font-mono">{analysis.entryZone[0]} – {analysis.entryZone[1]}</span>
                </div>
              )}
            </div>
          </Section>

          {/* Explanation (Phase 8 metadata: badge reflects whether prose is from Claude or templates) */}
          {analysis && (
            <Section
              title={explanationTitle}
              action={<FreshnessBadge freshness={explanationBadge} title={explanationTooltip} />}
            >
              <Tabs defaultValue="beginner" className="w-full">
                <TabsList className="w-full h-8">
                  <TabsTrigger value="beginner" className="text-xs flex-1">Beginner</TabsTrigger>
                  <TabsTrigger value="expert" className="text-xs flex-1">Expert</TabsTrigger>
                </TabsList>
                <TabsContent value="beginner" className="mt-3">
                  <p className="text-xs text-muted-foreground leading-relaxed">{analysis.beginnerExplanation}</p>
                </TabsContent>
                <TabsContent value="expert" className="mt-3">
                  <p className="text-xs text-muted-foreground leading-relaxed">{analysis.expertExplanation}</p>
                </TabsContent>
              </Tabs>
            </Section>
          )}

          {/* Reasons For / Against */}
          {analysis && (
            <div className="grid grid-cols-2 gap-3">
              <div className="space-y-2">
                <h4 className="text-xs font-semibold text-bullish flex items-center gap-1">
                  <CheckCircle className="h-3 w-3" /> Reasons For
                </h4>
                <ul className="space-y-1">
                  {analysis.reasonsFor.map((r, i) => (
                    <li key={i} className="text-[11px] text-muted-foreground pl-3 relative before:absolute before:left-0 before:top-1.5 before:w-1.5 before:h-1.5 before:rounded-full before:bg-bullish/40">
                      {r}
                    </li>
                  ))}
                </ul>
              </div>
              <div className="space-y-2">
                <h4 className="text-xs font-semibold text-bearish flex items-center gap-1">
                  <XCircle className="h-3 w-3" /> Reasons Against
                </h4>
                <ul className="space-y-1">
                  {analysis.reasonsAgainst.map((r, i) => (
                    <li key={i} className="text-[11px] text-muted-foreground pl-3 relative before:absolute before:left-0 before:top-1.5 before:w-1.5 before:h-1.5 before:rounded-full before:bg-bearish/40">
                      {r}
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          )}

          {/* Fallback reasoning when no analysis */}
          {!analysis && (
            <Section title="AI Reasoning">
              <p className="text-xs text-muted-foreground leading-relaxed">{signal.ai_reasoning}</p>
            </Section>
          )}

          {/* Invalidation */}
          <Section title="Invalidation">
            <p className="text-xs text-muted-foreground leading-relaxed">
              {signal.invalidation_reason || analysis?.invalidation || "No invalidation condition specified."}
            </p>
          </Section>

          {/* Management Plan */}
          <Section title="Management Plan">
            <p className="text-xs text-muted-foreground leading-relaxed">
              Scale out at TP1, move SL to breakeven, trail to TP2/TP3. Reduce position size if confidence is below 60%.
            </p>
          </Section>

          {/* Warning footer */}
          <div className="rounded-lg border border-border bg-muted/30 p-3 flex items-start gap-2">
            <AlertTriangle className="h-3.5 w-3.5 text-warning mt-0.5 shrink-0" />
            <p className="text-[10px] text-muted-foreground leading-relaxed">
              This is AI-generated analysis for educational purposes only. Always do your own research and manage your risk. Past performance does not guarantee future results.
            </p>
          </div>
        </div>

        {/* Phase 18.3: Take Trade dialog, mounted once per drawer. */}
        <TakeTradeDialog
          open={takeTradeOpen}
          onOpenChange={setTakeTradeOpen}
          signal={signal}
        />
      </SheetContent>
    </Sheet>
  );
}

function Section({
  title,
  action,
  children,
}: {
  title: string;
  action?: React.ReactNode;
  children: React.ReactNode;
}) {
  return (
    <div className="space-y-2">
      <div className="flex items-center justify-between gap-2">
        <h3 className="text-xs font-semibold text-foreground uppercase tracking-wider">{title}</h3>
        {action}
      </div>
      {children}
    </div>
  );
}

function LevelRow({
  label,
  value,
  className,
  term,
}: {
  label: string;
  value: string | number;
  className?: string;
  /** Optional glossary term — when present the label hover-explains itself. */
  term?: GlossaryTerm;
}) {
  return (
    <div className="flex justify-between items-center">
      <span className="text-[11px] text-muted-foreground">
        {term ? <TermTooltip term={term}>{label}</TermTooltip> : label}
      </span>
      <span className={`text-xs font-mono font-medium ${className || "text-foreground"}`}>{value}</span>
    </div>
  );
}
